import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" suppressHydrationWarning>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class" // This tells next-themes to apply the theme as a class on the <html> element (e.g., <html class="dark">)
          defaultTheme="light" // Default to the user's system preference
          enableSystem // Enable system theme detection
          disableTransitionOnChange // Optional: disable transitions when theme changes
        >

          {children}
        </ThemeProvider>
      </body>
    </html>

  );
}
